spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
authentication:
  code:
    ttl: 5m

jwt:
  key:
    access: h9dHOdBnBQ2AVk5dX8wV3zXoxBwnlhk5P4gEQXyS5SOqqrmLI8odYKxdKwJg6FNUREFE3khJVtKHigcQWRp/aA==
    refresh: qifEPLE6seg6O6dGeuFw64S7WfrYrW372GGM2VK2NqWpuRxwaciw8hy2BjBJ3Fc2XeM52qGKGMeyhphFi9BPFA==
  ttl:
    access: 1h
    refresh: 5h


logging:
  level:
    org.jooq.tools: debug
    ru.qwonix.foxwhiskersapi: trace
    org.springframework.security: trace