spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
authentication:
  code:
    ttl: 5m

jwt:
  access-ttl: 1h
  refresh-ttl: 5h
  access-key: h9dHOdBnBQ2AVk5dX8wV3zXoxBwnlhk5P4gEQXyS5SOqqrmLI8odYKxdKwJg6FNUREFE3khJVtKHigcQWRp/aA==
  refresh-key: qifEPLE6seg6O6dGeuFw64S7WfrYrW372GGM2VK2NqWpuRxwaciw8hy2BjBJ3Fc2XeM52qGKGMeyhphFi9BPFA==

logging:
  level:
    org.jooq.tools: debug
    ru.qwonix.foxwhiskersapi: trace
    org.springframework.security: trace